#!/usr/bin/env python

import rospy
import roslib
import time
from std_msgs.msg import Float32, Int32
from geometry_msgs.msg import Twist
from dual_mc33926_rpi import motors, MAX_SPEED
from simple_pid import PID


class MotorEncoder():
    def __init__(self, enc_topic_name, velo_topic_name, pos_topic_name):
        rospy.Subscriber(enc_topic_name, Int32, self.steps_callback)
        self.velo_pub = rospy.Publisher(velo_topic_name, Float32, queue_size=10)
        self.pos_pub = rospy.Publisher(pos_topic_name, Float32, queue_size=10)
        self.direction = "forward"
        self.rad_per_step = 3.1415*2/140

        self.absolute_steps = 0
        self.time_stamp = 0
        self.last_absolute_steps = 0
        self.last_time_stamp = 0
        self.abs_offset = 0
        self.pos_offset = 0
        self.position = 0
        self.velocity = 0

        self.update_callback = None

    def set_onupdate_callback(self, update_callback):
        self.update_callback = update_callback

    def get_timestamp(self):
        return round(time.time() * 1000)

    def update_velocity(self):
        dt = (self.time_stamp - self.last_time_stamp)/1000.0
        if self.direction == "forward":
            tmp = (self.absolute_steps - self.last_absolute_steps)
        elif self.direction == "backward":
            tmp = -(self.absolute_steps - self.last_absolute_steps)
        else:
            raise "set_direction wrong direction %s"%self.direction
        if dt == 0:
            raise "timestamp is zero"

        self.velocity = self.rad_per_step * tmp / dt
        self.velo_pub.publish(self.velocity)

    def update_position(self):
        if self.direction == "forward":
            self.position = self.pos_offset + (self.absolute_steps - self.abs_offset)
        elif self.direction == "backward":
            self.position = self.pos_offset - (self.absolute_steps - self.abs_offset)
        else:
            raise "set_direction wrong direction %s"%self.direction
        self.pos_pub.publish(self.position)

    def steps_callback(self, msg):
        try:
            self.absolute_steps = msg.data
            self.time_stamp = self.get_timestamp()
            self.update_velocity()
            self.update_position()

            self.last_time_stamp = self.time_stamp
            self.last_absolute_steps  = self.absolute_steps
            if self.update_callback is not None:
                self.update_callback()
        except Exception as e:
            print(e)

    def set_direction(self, direction):
        if direction in ["forward", "backward"]:
            if self.velocity == 0:
                self.direction = direction
                self.abs_offset = self.absolute_steps
                self.pos_offset = self.position
            else:
                raise "cannot change direction with velocity=%f != 0"%self.velocity
        else:
            raise "set_direction wrong direction %s"%direction

    def get_position(self):
        return self.position

    def get_velocitiy(self):
        return self.velocity

class MotorController:
    def __init__(self, encoder, motor, name):
        self.encoder_name = name
        self.motor = motor
        self.motor.enable()
        self.motor.setSpeed(0)
        self.encoder = encoder
        self.max_pwm = 200
        self.encoder.set_onupdate_callback(self.on_update)

        self.last_pwm_value = 0

        self.velo_pid = PID(0, 5, 0, setpoint=0)
        self.pos_pid = PID(2, 0.3, 0, setpoint=0)

        self.velocity_goal = None
        self.position_goal = None

        rospy.Subscriber('motor/velocity_goal/'+name, Float32, self.set_velocity_callback)
        rospy.Subscriber('motor/position_goal/'+name, Float32, self.set_position_callback)

    def update_pwm_value(self, new_pwm_value):
        ist_velo = self.encoder.get_velocitiy()
        if self.last_pwm_value > 0 and new_pwm_value < 0 and ist_velo != 0:
            self.motor.setSpeed(0)
            print("stop")
            return
        elif self.last_pwm_value < 0 and new_pwm_value > 0 and ist_velo != 0:
            self.motor.setSpeed(0)
            print("stop")
            return
        elif self.last_pwm_value >= 0 and new_pwm_value < 0 and ist_velo == 0:
            self.encoder.set_direction("backward")
            print("backward")
        elif self.last_pwm_value <= 0 and new_pwm_value > 0 and ist_velo == 0:
            self.encoder.set_direction("forward")
            print("forward")
        if new_pwm_value > self.max_pwm:
            new_pwm_value = self.max_pwm
        if new_pwm_value < -self.max_pwm:
            new_pwm_value = -self.max_pwm
        self.motor.setSpeed(new_pwm_value)
        self.last_pwm_value = new_pwm_value

    def on_update(self):
        if self.velocity_goal is not None:
            #ist_velo = self.encoder.get_velocitiy()
            #pwm_value = -int(6*self.velocity_goal)
            #self.update_pwm_value(pwm_value)
            pass
        if self.position_goal is not None:
            ist_pos = self.encoder.get_position()
            print("istpoint %d"%ist_pos)
            print("setpoint %d"%self.position_goal)
            self.pos_pid.setpoint = self.position_goal
            pwm_value = int(self.pos_pid(ist_pos))
            print("pwm_value %d"%pwm_value)
            self.update_pwm_value(pwm_value)

    def set_velocity(self, velo):
        self.velocity_goal = velo
        self.position_goal = None

    def set_position(self, pos):
        self.velocity_goal = None
        self.position_goal = pos

    def set_velocity_callback(self, msg):
        self.set_velocity(msg.data)

    def set_position_callback(self, msg):
        self.set_position(msg.data)
    

#############################################################
#############################################################
class DifferentialDrive():
#############################################################
#############################################################

    #############################################################
    def __init__(self):
    #############################################################
        rospy.init_node("drive")
        nodename = rospy.get_name()
        rospy.loginfo("%s started" % nodename)

        self.w = rospy.get_param("~base_width", 0.2)

        self.left_encoder = MotorEncoder('encoder/setps_left','encoder/velo_left','encoder/pos_left')
        self.right_encoder = MotorEncoder('encoder/setps_right','encoder/velo_right','encoder/pos_right')

        rospy.Subscriber('cmd_vel', Twist, self.twistCallback)

        self.rate = rospy.get_param("~rate", 50)
        self.timeout_ticks = rospy.get_param("~timeout_ticks", 2)
        self.left = 0
        self.right = 0

        self.left_motor = MotorController(self.left_encoder, motors.motor2, "left")
        self.right_motor = MotorController(self.right_encoder, motors.motor1, "right")

        #self.right_motor.set_velocity(44)

    #############################################################
    def spin(self):
    #############################################################

        r = rospy.Rate(self.rate)
        idle = rospy.Rate(10)
        then = rospy.Time.now()
        self.ticks_since_target = self.timeout_ticks

        ###### main loop  ######
        while not rospy.is_shutdown():

            while not rospy.is_shutdown() and self.ticks_since_target < self.timeout_ticks:
                self.spinOnce()
                r.sleep()
            idle.sleep()

    #############################################################
    def spinOnce(self):
    #############################################################

        self.right = 1.0 * self.dx + self.dr * self.w * 2
        self.left = 1.0 * self.dx - self.dr * self.w * 2

        max_speed = 0.5

        if abs(self.left) > max_speed or abs(self.right) > max_speed:
               scale = max_speed/max(abs(self.left),abs(self.right))
               self.left *= scale
               self.right *= scale

        self.left = int(-MAX_SPEED*self.left)
        self.right = int(MAX_SPEED*self.right)

        self.left_motor.set_velocity(self.left)
        self.right_motor.set_velocity(self.right)

        self.ticks_since_target += 1

    #############################################################
    def twistCallback(self,msg):
    #############################################################

        self.ticks_since_target = 0
        self.dx = msg.linear.x
        self.dr = msg.angular.z


#############################################################
#############################################################
def main():
    try:
        twistToMotors = DifferentialDrive()
        twistToMotors.spin()
    except rospy.ROSInterruptException:
        pass
    motors.motor1.setSpeed(0)
    motors.motor2.setSpeed(0)
    motors.disable()


if __name__ == '__main__':
    main()
